### ISSUE TITLE
bind

### ISSUE THREAD

**Issue by sbernhard** [cmvee/bt-presence#2]
In case I'm stopping and starting btPresence again, I get:

TypeError: Cannot read property 'bind' of undefined

2|node-red | 18 Dec 23:23:52 - [error] [bt-presence:41b0680f.ecda98] TypeError: Cannot read property 'bind' of undefined
2|node-red |     at btPresence.start (/home/pi/nodes/node_modules/bt-presence/index.js:130:37)

**Comment by cmvee** [comment]
Thanks for filing the issue. You are correct. This was a bug. It is now resolved in [2.0.0](https://github.com/cmvee/bt-presence/tree/2.0.0)
