### ISSUE TITLE
setcap privileges to run l2ping

### ISSUE THREAD

**Issue by johnwalicki** [cmvee/bt-presence#4]
You might want to add some documentation to the README.md that l2ping needs to run as root.
Grant root privileges to run the l2ping scan by issuing this command:
$ sudo setcap 'cap_net_raw+eip' \`which l2ping\`

**Comment by cmvee** [comment]
Thanks much! Added to the README in [2.0.0](https://github.com/cmvee/bt-presence/tree/2.0.0)
