### ISSUE TITLE
bt-presence needs 2 pings

### ISSUE THREAD

**Issue by johnwalicki** [cmvee/bt-presence#5]
It seems that l2ping on my Linux system fails for the first ping but succeeds after that. As a test, I was scanning for my phone. I had to adjust the bt-presence index.js to send 2 pings.

$ sudo l2ping -c 3 -t 5 B0:C5:59:9C:9C:EE
Ping: B0:C5:59:9C:9C:EE from A4:34:D9:5A:45:77 (data size 44) ...
no response from B0:C5:59:9C:9C:EE: id 0
0 bytes from B0:C5:59:9C:9C:EE id 1 time 784.26ms
0 bytes from B0:C5:59:9C:9C:EE id 2 time 19.07ms
3 sent, 2 received, 33% loss

**Comment by cmvee** [comment]
Thanks for your input. I haven't had that experience but took note.

The new version, [2.0.0](https://github.com/cmvee/bt-presence/tree/2.0.0), lets you configure this via the setScanOptions({ count: 3, timeoutSecs: 8 }) method.

**Comment by johnwalicki** [comment]
The good news is that using bt-presence 2.0.0, I am not experiencing the dropped initial l2ping. I've also restarted my phone since my last experiment.  In either case, its working for me. Thanks for the setScanOptions() function.
